name: CI Minikube

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - develop

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build and deploy myservice to minikube

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Kubernetes Minikube
        uses: medyagh/setup-minikube@master

      - name: Try the Kubernetes cluster
        run: |
          kubectl get nodes
          kubectl get pods -A

      - name: Build Docker image inside Minikube
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)

          docker build -t local/myservice:latest ./MyService

          echo "Verifying Docker images:"
          docker images

      - name: Deploy the image to Minikube
        run: |
          kubectl apply -f k8s/deployment-service.yaml

      - name: Update deployment with local image
        run: |
          kubectl set image deployment/myservice-deployment myservice=local/myservice:latest
          kubectl rollout status deployment/myservice-deployment --timeout=120s

      - name: Get Kubernetes service URL
        run: |
          kubectl wait --for=condition=Ready --timeout=120s pod -l app=myservice
          kubectl get pods
          kubectl get services
          minikube service list
          minikube service myservice-service --url
          echo "------------------ service ready ------------------"

      - name: Test Kubernetes service URL
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 10
          max_attempts: 5
          command: curl $(minikube service myservice-service --url)

      - name: Log Kubernetes pods
        if: always()
        run: |
          kubectl logs -l app=myservice --tail=100